# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación al contenedor
COPY . .

# Instalar dependencias del sistema (enchant-2 y hunspell-es)
RUN apt-get update && \
    apt-get install -y --no-install-recommends enchant-2 hunspell-es && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Instalar las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto en el que corre la aplicación (si es necesario)
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "main.py"]