# Generated by Django 5.1.6 on 2025-03-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='clarification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.classification', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='clarification',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classification.classification', verbose_name='Clasificación'),
        ),
    ]
