# Generated by Django 5.1.6 on 2025-03-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_clarification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='clarification',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='historicalcomment',
            old_name='clarification',
            new_name='classification',
        ),
    ]
