# Generated by Django 5.1.6 on 2025-03-10 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_clarification_comment_classification_and_more'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='source.source', verbose_name='Fuente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='source.source', verbose_name='Fuente'),
        ),
    ]
