# Generated by Django 5.1.6 on 2025-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_source_historicalcomment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_owner',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Usuario propietario'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='user_owner',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Usuario propietario'),
        ),
    ]
