# Generated by Django 5.1.6 on 2025-03-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_user_owner_historicalcomment_user_owner'),
        ('comment_user_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_user_owner.userowner', verbose_name='Usuario Propietario'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='user_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment_user_owner.userowner', verbose_name='Usuario Propietario'),
        ),
    ]
