# Generated by Django 5.1.6 on 2025-04-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_classification_classification_type_and_more'),
        ('comment', '0006_alter_comment_user_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='classification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classification.classification'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='classification',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='classification.classification'),
        ),
    ]
