# Generated by Django 5.1.6 on 2025-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comment_user_alter_historicalcomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
