# Generated by Django 5.1.6 on 2025-04-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_comment_is_read_historicalcomment_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='is_read',
        ),
    ]
