# Generated by Django 5.1.6 on 2025-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_remove_comment_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='text',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
