# Generated by Django 5.1.6 on 2025-05-31 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_alter_comment_text_alter_historicalcomment_text'),
        ('messenger', '0002_remove_conversation_id_messenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='messenger_conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='messenger.conversation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='messenger_created_at',
            field=models.DateTimeField(default=None, verbose_name='Fecha de creación en messenger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='messenger_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='ID de Messenger'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='messenger_conversation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='messenger.conversation'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='messenger_created_at',
            field=models.DateTimeField(default=None, verbose_name='Fecha de creación en messenger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='messenger_id',
            field=models.CharField(db_index=True, editable=False, max_length=50, null=True, verbose_name='ID de Messenger'),
        ),
    ]
