# Generated by Django 5.1.6 on 2025-05-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_comment_messenger_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='messenger_id',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name='ID de Messenger'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='messenger_id',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True, verbose_name='ID de Messenger'),
        ),
    ]
