version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: z17-mitrans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    container_name: opicuba_server
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    container_name: opicuba_celery
    build: .
    command: celery -A core worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    container_name: opicuba_celery_beat
    build: .
    command: celery -A core beat --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: