# Generated by Django 5.1.6 on 2025-03-03 21:01

from django.db import migrations
import uuid
from apps.classification.classifications import classifications

def load_initial_data(apps, schema_editor):
    Classification = apps.get_model('classification', 'Classification')
    Classification.objects.bulk_create([
        Classification(name=data['name'], external_id=f"clas_{uuid.uuid4().hex}")
        for data in classifications
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]