# Generated by Django 5.1.6 on 2025-04-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20250303_2201'),
        ('comment', '0006_alter_comment_user_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='classification_type',
            field=models.CharField(default=True, max_length=100, verbose_name='Tipo de clasificación'),
        ),
        migrations.AddField(
            model_name='classification',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications_comment', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='historicalclassification',
            name='classification_type',
            field=models.CharField(default=True, max_length=100, verbose_name='Tipo de clasificación'),
        ),
        migrations.AddField(
            model_name='historicalclassification',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment.comment'),
        ),
    ]
