# Generated by Django 5.1.6 on 2025-05-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment_user_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id_messenger', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_user_owner.userowner', verbose_name='Usuario Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_messenger', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.conversation')),
                ('sender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_user_owner.userowner', verbose_name='Usuario Propietario')),
            ],
        ),
    ]
