# Generated by Django 5.1.6 on 2025-05-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id_messenger',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='messenger_id',
            field=models.CharField(default=None, editable=False, max_length=50, unique=True, verbose_name='ID de Messenger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='messenger_updated_at',
            field=models.DateTimeField(default=None, verbose_name='Fecha de modificación en messenger'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
