# Generated by Django 5.1.6 on 2025-06-03 15:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_user_owner', '0002_historicaluserowner_entity_userowner_entity'),
        ('messenger', '0002_remove_conversation_id_messenger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Link de la conversación'),
        ),
        migrations.CreateModel(
            name='HistoricalConversation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('messenger_id', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='ID de Messenger')),
                ('link', models.CharField(max_length=100, verbose_name='Link de la conversación')),
                ('messenger_updated_at', models.DateTimeField(verbose_name='Fecha de modificación en messenger')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comment_user_owner.userowner', verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'historical conversation',
                'verbose_name_plural': 'historical conversations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
