# Generated by Django 5.1.6 on 2025-06-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_answer_sent',
            field=models.BooleanField(default=False, verbose_name='El sistema le respodio al usuario.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_user_reply_received',
            field=models.BooleanField(default=False, verbose_name='Se recivio la respuesta correcta del usuario.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_answer_date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la ultima respuesta enviada'),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='is_answer_sent',
            field=models.BooleanField(default=False, verbose_name='El sistema le respodio al usuario.'),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='is_user_reply_received',
            field=models.BooleanField(default=False, verbose_name='Se recivio la respuesta correcta del usuario.'),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='last_answer_date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de la ultima respuesta enviada'),
        ),
    ]
