# Generated by Django 5.1.6 on 2025-06-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_conversation_is_answer_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_final_answer_sent',
            field=models.BooleanField(default=False, verbose_name='Se envió la respuesta final al usuario.'),
        ),
        migrations.AddField(
            model_name='historicalconversation',
            name='is_final_answer_sent',
            field=models.BooleanField(default=False, verbose_name='Se envió la respuesta final al usuario.'),
        ),
    ]
