# Generated by Django 5.1.6 on 2025-06-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_user_owner', '0002_historicaluserowner_entity_userowner_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserowner',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='userowner',
            name='entity',
        ),
    ]
