# Generated by Django 5.1.6 on 2025-06-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_user_owner', '0003_remove_historicaluserowner_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserowner',
            name='facebook_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, verbose_name='ID de usuario en Facebook'),
        ),
        migrations.AddField(
            model_name='userowner',
            name='facebook_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='ID de usuario en Facebook'),
        ),
    ]
