# Generated by Django 5.1.6 on 2025-06-23 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_user_owner', '0004_historicaluserowner_facebook_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserowner',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='historicaluserowner',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Ej: 51234567 (8 dígitos, sin '+53', espacios o guiones).", max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='El numero debe de tener 8 digitos y comenzar por 5, 6 o 7 (Ej: 51234567)', regex='^[5-7]\\d{7}$')]),
        ),
        migrations.AddField(
            model_name='historicaluserowner',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='userowner',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='userowner',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Ej: 51234567 (8 dígitos, sin '+53', espacios o guiones).", max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='El numero debe de tener 8 digitos y comenzar por 5, 6 o 7 (Ej: 51234567)', regex='^[5-7]\\d{7}$')]),
        ),
        migrations.AddField(
            model_name='userowner',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
    ]
