# Generated by Django 5.1.6 on 2025-06-24 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_user_owner', '0005_historicaluserowner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserowner',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Ej: 51234567 (8 dígitos, sin '+53', espacios o guiones).", max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El numero debe de tener 8 digitos y comenzar por 5, 6 o 7 (Ej: 51234567)', regex='^[5-7]\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='userowner',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Ej: 51234567 (8 dígitos, sin '+53', espacios o guiones).", max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El numero debe de tener 8 digitos y comenzar por 5, 6 o 7 (Ej: 51234567)', regex='^[5-7]\\d{7}$')]),
        ),
    ]
