# Generated by Django 5.1.6 on 2025-06-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_user_owner', '0006_alter_historicaluserowner_phone_number_and_more'),
        ('user', '0007_alter_facebookpage_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserowner',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.entity', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='userowner',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.entity', verbose_name='Entidad'),
            preserve_default=False,
        ),
    ]
