# Generated by Django 5.1.6 on 2025-03-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluseraccount',
            name='external_id',
            field=models.CharField(db_index=True, default='user_asdasd12345asd', editable=False, max_length=50, verbose_name='ID externo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='external_id',
            field=models.CharField(default='user_asdlkj564123asd', editable=False, max_length=50, unique=True, verbose_name='ID externo'),
            preserve_default=False,
        ),
    ]
