# Generated by Django 5.1.6 on 2025-03-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicaluseraccount_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluseraccount',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super Usuario'), ('manager', 'Gestor'), ('consultant', 'Consultor')], default='consultant', max_length=10, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super Usuario'), ('manager', 'Gestor'), ('consultant', 'Consultor')], default='consultant', max_length=10, verbose_name='Rol'),
        ),
    ]
