# Generated by Django 5.1.6 on 2025-06-03 15:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_historicaluseraccount_role_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ID externo')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre de Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.RenameField(
            model_name='historicaluseraccount',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='historicaluseraccount',
            name='entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.entity', verbose_name='Entidad'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='entity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.entity', verbose_name='Entidad'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ID externo')),
                ('facebook_access_token', models.CharField(max_length=255, null=True, verbose_name='Token de acceso a Facebook')),
                ('facebook_page_id', models.CharField(max_length=255, null=True, verbose_name='ID de la página de Facebook')),
                ('facebook_page_name', models.CharField(max_length=255, null=True, verbose_name='Nombre de la página de Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.entity', verbose_name='Entidad')),
            ],
            options={
                'verbose_name': 'Página de Facebook',
                'verbose_name_plural': 'Páginas de Facebook',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='ID externo')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Nombre de Usuario')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Entidad',
                'verbose_name_plural': 'historical Entidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFacebookPage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='ID externo')),
                ('facebook_access_token', models.CharField(max_length=255, null=True, verbose_name='Token de acceso a Facebook')),
                ('facebook_page_id', models.CharField(max_length=255, null=True, verbose_name='ID de la página de Facebook')),
                ('facebook_page_name', models.CharField(max_length=255, null=True, verbose_name='Nombre de la página de Facebook')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.entity', verbose_name='Entidad')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Página de Facebook',
                'verbose_name_plural': 'historical Páginas de Facebook',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
