# Generated by Django 5.1.6 on 2025-06-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.entity', verbose_name='Entidad'),
        ),
    ]
