# Generated by Django 5.1.6 on 2025-06-24 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_entity_is_active_historicalentity_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to='user.entity', verbose_name='Entidad'),
        ),
    ]
